config/routes.rb
Rails.application.routes.draw do

  get 'candies/index'

  get 'candies/show'

  get 'candies/new'

  get 'candies/edit'

  root to: 'candy_stores#index'

  resources :candy_stores do
    resources :candies
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candy.rb
class Candy < ApplicationRecord

  belongs_to :candy_store

  validates_presence_of :name, :cost

  def info
    "The #{name}."
  end

end

app/models/candy_store.rb
class CandyStore < ApplicationRecord

  has_many :candies

  validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  before_action :candy_store

  before_action :candy, except: [:index, :new, :create]

  def index
    @candies = @candy_store.candies
  end

  def show
  end

  def new
    @candy = Candy.new
  end

  def create
    @candy = @candy_store.candies.new(candy_params)
    if @candy.save
      redirect_to candy_store_candy_path(@candy_store, @candy)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @candy.update(candy_params)
      redirect_to candy_store_candy_path(@candy_store, @candy)
    else
      render :edit
    end
  end

  def destroy
    @candy.destroy
    redirect_to candy_store_candies_path(@candy_store)
  end

  private

    def candy_params
      params.require(:candy).permit(:name, :cost, :allergens, :calories, :ranking)
    end

    def candy_store
      @candy_store = CandyStore.find(params[:candy_store_id])
    end

    def candy
      @candy = @candy_store.candies.find(params[:id])
    end
end

app/controllers/candy_stores_controller.rb
class CandyStoresController < ApplicationController
  before_action :candy_store, except: [:index, :new, :create]
  def index
    @candy_stores = CandyStore.all
  end

  def show
  end

  def new
    @candy_store = CandyStore.new
  end

  def create
    @candy_store = CandyStore.new(candy_store_params)
    if @candy_store.save
      redirect_to candy_store_path(@candy_store)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @candy_store.update(candy_store_params)
      redirect_to candy_store_path(@candy_store)
    else
      render :edit
    end
  end

  def destroy
    @candy_store.destroy
    redirect_to candy_stores_path
  end

  private

  def candy_store_params
    params.require(:candy_store).permit(:name, :address, :phone, :hours)
  end

  def candy_store
    @candy_store = CandyStore.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candies_helper.rb
module CandiesHelper
end

app/helpers/candy_store_helper.rb
module CandyStoreHelper
end

app/views/candies/_form.html.erb
<%= form_for [@candy_store, @candy] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br/>
  <%= f.label :cost %>
  <%= f.number_field :cost, required: true %>
  <br/>
  <%= f.label :allergens %>
  <%= f.check_box :allergens %>
  <br/>
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  <br/>
  <%= f.label :ranking %>
  <%= f.select :ranking, (1..10).to_a%>
  <br/>
  <%= f.submit %>
<% end %>

app/views/candies/edit.html.erb
<h1>Editing: <%= @candy.info %></h1>
<%= render(partial: 'form') %>

app/views/candies/index.html.erb
<h1><%= @candy_store.name %>- Inventory</h1>

<% if @candies.any? %>
  <ul>
    <% @candies.each do |candy| %>
    <li class="list"><%= candy.info %> - <%= link_to 'Show', candy_store_candy_path(@candy_store, candy)%></li>
    <% end %>
  </ul>
  <% else %>
    <h3>No candy listed yet, please add some</h3>
  <% end %>

<%= link_to 'Add candy to Inventory', new_candy_store_candy_path(@candy_store) %>
<%= link_to 'Return to Candy Shoppes', candy_stores_path %>

app/views/candies/new.html.erb
<h1>Create A New Candy For: <%= @candy_store.name %></h1>

<%= render(partial: 'form') %>

app/views/candies/show.html.erb
<h1><%= @candy.info %></h1>

<p> Cost: $<%= @candy.cost %> </p>
<p> Allergens: <%= @candy.allergens %> </p>
<p> Calories: <%= @candy.calories %> </p>
<p> Ranking: <%= @candy.ranking%> </p>

<%= link_to 'Edit Candy', edit_candy_store_candy_path(@candy_store, @candy) %>
<%= link_to 'Delete Candy', candy_store_candy_path(@candy_store, @candy),
              method: :delete, data: {confirm: 'Really Delete?'}%>
<br/>
<%= link_to 'All Candy', candy_store_candies_path(@candy_store)%>

app/views/candy_stores/_form.html.erb
<% if @candy_store.errors.any? %>
  <ul>
    <% @candy_store.errors.full_message.each do |error| %>
      <li> <%error%></li>
    <% end %>
  </ul>
  <% end %>

  <%= form_for @candy_store do |f| %>
    <br/>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <br/>
    <%= f.label :phone %>
    <%= f.telephone_field :phone %>
    <br/>
    <%= f.label :hours %>
    <%= f.text_field :hours %>
    <br/>
    <%= f.submit %>

  <% end %>

app/views/candy_stores/edit.html.erb
<h1>Edit Candy Shoppe</h1>

<%= render(partial: 'form') %>

app/views/candy_stores/index.html.erb
<h1>Candy Shoppes</h1>

<% if @candy_stores.any? %>

  <ul>
    <% @candy_stores.each do |store| %>
      <li class="list">
        <%= link_to store.name, candy_store_path(store)%>
      </li>
    <% end %>
  </ul>

<% else %>

<% end %>

<%= link_to 'Create A Shoppe', new_candy_store_path %>

app/views/candy_stores/new.html.erb
<h1>Enter A New Candy Shoppe</h1>

<%= render(partial: 'form') %>

app/views/candy_stores/show.html.erb
<h1>Candy Shoppe <%= @candy_store.name %> Info</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= @candy_store.address %> </td>
      <td> <%= @candy_store.phone %> </td>
      <td> <%= @candy_store.hours %> </td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit Shoppe', edit_candy_store_path(@candy_store) %>
<%= link_to 'Delete Shoppe', candy_store_path(@candy_store), method: :delete %>
<%= link_to "#{@candy_store.name.pluralize} Inventory", candy_store_candies_path(@candy_store) %>

<%= link_to 'All Shoppes', candy_stores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CandyShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>